<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>KewlStreams.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="KewlStreams.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TwitchLib" Version="3.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KewlKommon\KewlKommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="KewlStreams Banner.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="KewlStreams Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libdave.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libsodium.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="opus.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
