<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>KewlTewns.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="KewlTewns.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.75.0.4178" />
    <PackageReference Include="VideoLibrary" Version="3.3.1" />
    <PackageReference Include="Xabe.FFmpeg" Version="6.0.2" />
    <PackageReference Include="Xabe.FFmpeg.Downloader" Version="6.0.2" />
    <PackageReference Include="YoutubeExplode" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KewlKommon\KewlKommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configs\config_template.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="KewlTewns Banner.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="KewlTewns Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libdave.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libsodium.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="opus.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\4nhPxFg73EY%28%28%29%28%29%28%29%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\agewO1vCllQ%28%28%28%28%29%28%29%28%28%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\Agp9ZXnYsjw%29%28%28%29%29%28%29%28%28%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\AQlfAyLfMX4%29%29%28%28%29%28%29%28%29%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\cz8rL6dwxFg%28%28%28%29%28%28%28%29%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\dvWP7dk42Ek%28%28%29%29%28%28%29%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\fTldoqanI1A%28%29%28%28%28%28%28%28%29%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\giRc4-iumwI%28%28%29%28%28%28%28%28%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\gyKSsscH1yc%28%28%29%29%28%28%28%29%28%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\hAUrbKmnzdw%28%29%29%28%28%29%28%28%28%28%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\iMfXLRSElWc%28%29%28%29%29%29%29%29%28%29%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\iUmdsf34i8M%28%29%28%28%28%28%28%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\Lj7L5rxxOdg%29%28%29%28%28%28%29%28%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\MUj6blC8f_E%29%29%28%28%28%29%28%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\Q40w2PMJg0U%29%28%29%29%29%28%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\QTYfN1zvyGo%29%29%29%28%29%28%28%28%29%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\TeW3p37nkic%29%28%29%28%28%28%28%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\TmLxPMKsvmA%29%28%29%28%29%29%29%28%28%28%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\tpZq40_fW-k%28%28%29%28%28%29%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\TZ6IY35sdJA%29%29%29%29%28%28%29%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\VqTfTker10c%29%28%29%28%29%28%28%28%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\YUgvJagtIf4%29%29%28%28%29%28%28%28%29%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\zW6UaIZrxeE%28%29%29%28%29%29%28%28%28%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\ZxmGMbSCxTY%29%28%28%29%29%28%29%29%28%29%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\_0NpA7haK1g%29%28%29%28%28%29%28.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tewns\_yJoqiBTy-M%28%29%28%28%28%29%29%28%29.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
