<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>KewlTewns.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="KewlTewns.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.75.0.4178" />
    <PackageReference Include="VideoLibrary" Version="3.3.1" />
    <PackageReference Include="Xabe.FFmpeg" Version="6.0.2" />
    <PackageReference Include="Xabe.FFmpeg.Downloader" Version="6.0.2" />
    <PackageReference Include="YoutubeExplode" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KewlKommon\KewlKommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configs\config_template.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="KewlTewns Banner.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="KewlTewns Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libdave.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libsodium.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="opus.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
